name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: self-hosted
    
    steps:
    - name: Git checkout
      run: cd /home/evote/backend && git pull
    - name: Install Dependencies
      run: cd /home/evote/backend && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
